#define CHARYBDIS_MINIMUM_DEFAULT_DPI 1500
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200
#define CHARYBDIS_MINIMUM_SNIPING_DPI 200
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 200
#define CHARYBDIS_DRAGSCROLL_REVERSE_X
#define CHARYBDIS_CARRET_REVERSE_X


#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define NO_USB_STARTUP_CHECK


