BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
SWAP_HANDS_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
MOUSE_SHARED_EP = yes

SPLIT_KEYBOARD = yes

DEFAULT_FOLDER = handwired/tractyl_manuform/5x6_right/teensy2pp


LINK_TIME_OPTIMIZATION_ENABLE = yes
SPACE_CADET_ENABLE = no
LTO_ENABLE = yes